name: Auto Pull on Server

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd C:\Users\ani20168\Desktop\Natalie-bot
          git fetch --all
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
